try to fix multiple bugs
1. job page modal popup - add employee is not working
2. after invitation - phone number is missing
3. mobile app job completition should  - customer name and employee name should be auto fill
3. mobile app job completition - remove the reenter the customer name
4. email - invoice price is showing in dollar (please check every where currency should be coming form settings)
5. call recording is not playing, call recording is showing this erro also -
 TypeError: o.map is not a function
    at eu (832451caa5565547.js:1:21996)
    at av (/_next/static/chunks/07504415fa2e35f4.js:1:62314)
    at oY (/_next/static/chunks/07504415fa2e35f4.js:1:82587)
    at io (/_next/static/chunks/07504415fa2e35f4.js:1:94019)
    at sc (/_next/static/chunks/07504415fa2e35f4.js:1:137040)
    at /_next/static/chunks/07504415fa2e35f4.js:1:136885
    at ss (/_next/static/chunks/07504415fa2e35f4.js:1:136893)
    at u9 (/_next/static/chunks/07504415fa2e35f4.js:1:132818)
    at sV (/_next/static/chunks/07504415fa2e35f4.js:1:158413)
    at MessagePort.O (/_next/static/chunks/07504415fa2e35f4.js:1:7372)
overrideMethod @ chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/installHook.js:1
d @ /_next/static/chunks/07504415fa2e35f4.js:1
oI @ /_next/static/chunks/07504415fa2e35f4.js:1
o.componentDidCatch.e.callback @ /_next/static/chunks/07504415fa2e35f4.js:1
lG @ /_next/static/chunks/07504415fa2e35f4.js:1
lY @ /_next/static/chunks/07504415fa2e35f4.js:1
iv @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
ui @ /_next/static/chunks/07504415fa2e35f4.js:1
i2 @ /_next/static/chunks/07504415fa2e35f4.js:1
sb @ /_next/static/chunks/07504415fa2e35f4.js:1
sh @ /_next/static/chunks/07504415fa2e35f4.js:1
u7 @ /_next/static/chunks/07504415fa2e35f4.js:1
u9 @ /_next/static/chunks/07504415fa2e35f4.js:1
sV @ /_next/static/chunks/07504415fa2e35f4.js:1
O @ /_next/static/chunks/07504415fa2e35f4.js:1
postMessage
i @ /_next/static/chunks/07504415fa2e35f4.js:1
n.unstable_scheduleCallback @ /_next/static/chunks/07504415fa2e35f4.js:1
sB @ /_next/static/chunks/07504415fa2e35f4.js:1
sU @ /_next/static/chunks/07504415fa2e35f4.js:1
(anonymous) @ /_next/static/chunks/07504415fa2e35f4.js:1
 View component error: TypeError: o.map is not a function
    at eu (832451caa5565547.js:1:21996)
    at av (/_next/static/chunks/07504415fa2e35f4.js:1:62314)
    at oY (/_next/static/chunks/07504415fa2e35f4.js:1:82587)
    at io (/_next/static/chunks/07504415fa2e35f4.js:1:94019)
    at sc (/_next/static/chunks/07504415fa2e35f4.js:1:137040)
    at /_next/static/chunks/07504415fa2e35f4.js:1:136885
    at ss (/_next/static/chunks/07504415fa2e35f4.js:1:136893)
    at u9 (/_next/static/chunks/07504415fa2e35f4.js:1:132818)
    at sV (/_next/static/chunks/07504415fa2e35f4.js:1:158413)
    at MessagePort.O (/_next/static/chunks/07504415fa2e35f4.js:1:7372) {componentStack: '\n    at eu (https://fieseros.com/_next/static/chun…_next/static/chunks/07504415fa2e35f4.js:1:222140)'}
6. every where number should add the country code

before start the development please share me your finding and plan